clubmatbackend:
    build: ./backend
    volumes:
      - ./backend/clubmat-backend:/clubmat-backend
    links:
      - clubmatdb
clubmatdb:
    build: ./db
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306